### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by Til7701** [JayPi4c/MinecraftDiscordIPBot#1]
Ich will Ports mit Benennung des services hinzufügen können! Und entscheiden können, ob "https://" oder "http://" oder nix davor stehen soll! 

Wie kommst du nicht von selbst darauf????

**Comment by JayPi4c** [comment]
Was hältst du davon, die .env zu erweitern?
```
BOTTOKEN=Your_Bot_Token
CLIENT_ID=123456789
GUILD_ID=123456789
CLEAR_COMMANDS="false"
PORT=1234
HTTPS=true
```
Ggf. kann man auch die Angaben zur Runtime mit Discord-Commands ändern. Das sollte aber nur gehen, wenn man die Rechte hat. Ein Rechtesystem wäre aber ziemlich viel...

**Comment by Til7701** [comment]
Können wir das um einen Port für die Map erweitern? Also:
```
SERVER_PORT=1234
MAP_PORT=1235
MAP_HTTPS=true
```

Also könnte die Ausgabe so aussehen: 
```
Server: 1.1.1.1:1234
Map: https://1.1.1.1:1235
```

**Comment by JayPi4c** [comment]
Das geht, aber dann sollte die map direkt in die Erstellung des docker images eingebettet werden, ansonsten haben wir da einen Port erreichbar, der keinen Nutzen hat.

**Comment by JayPi4c** [comment]
Ich habe mir gerade nochmal ein paar Gedanken gemacht. Am besten wäre wahrscheinlich, zwei compose Dateien zu erstellen. Eine inklusive Map und eine mit einem Vanilla Server. Cooler wäre es natürlich, wenn man eine Datei hätte und diese anhand der Umgebungsvariablen erkennt, welcher Container zu starten ist. Aber soweit ich weiß gibt es keinen conditional Startup von Containern in Compose. Und ein extra Script zu schreiben, dass die richtigen Container startet ist nicht angemessen, wenn man es beispielsweise mit Portainer nutzen möchte. Dabei ginge die Portabilität von Docker und compose ein wenig verloren.
Außerdem sollte sich in dem Zusammenhang dann direkt auch mit dem Plugin System von Minecraft Docker beschäftigt werden:
https://github.com/itzg/docker-minecraft-server#working-with-mods-and-plugins
